### ISSUE TITLE
Include (some?) generated artifacts in the repository

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/tree-sitter-sqlrest#1]
As a general rule, I don't save generated files in version control repositories. But the convention for tree-sitter grammars seems to be that the generated files *are* stored in the repository. My current editor [Helix](https://helix-editor.com/) uses tree-sitter extensively, as defined in this [languages.toml](https://github.com/helix-editor/helix/blob/master/languages.toml) file, and all the tree-sitter grammars that I checked include (some?) of the generated files in the repo.

@ckindermann Please figure out what the convention is and let's adopt it.

**Comment by ckindermann** [comment]
I couldn't find any explicit conventions for tree-sitter other than what is written [here](https://tree-sitter.github.io/tree-sitter/creating-parsers#project-setup) about a repository's name. So, I looked at popular tree-sitter repositories (popular meaning they have more than 100 stars on GitHub), e.g, [Bash](https://github.com/tree-sitter/tree-sitter-bash), [Python](https://github.com/tree-sitter/tree-sitter-python), [C](https://github.com/tree-sitter/tree-sitter-c), [Go](https://github.com/tree-sitter/tree-sitter-go), [JavaScript](https://github.com/tree-sitter/tree-sitter-javascript), [Markdown](https://github.com/ikatyang/tree-sitter-markdown). They all include source files generated via `tree-sitter generate`, i.e,

- `binding.gyp`
- `bindings`
- `Cargo.toml`
- `grammar.js`
- `LICENSE`
- `package.json`
- `src`

I also noticed that these generated files are sometimes modified, e.g., to alter the behavior of the parser. So, it seems to me that we should also keep these generated files under version control.

**Comment by jamesaoverton** [comment]
Ok, let's add the generated files to the repository.
